server:
  port: 5200

spring:
  application:
    name: multilogin
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/multilogin_system?allowPublicKeyRetrieval=TRUE&useSSL=FALSE
    username:
    password: 
    drive-class-name: mysql.cj.jdbc.Driver
  jpa:
    # database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
    database: mysql
    open-in-view: false
